#!python

import sys
import numpy as np
from PIL import Image

def main(argv):
    length = len(argv)
    if length < 4:
        print("Usage:")
        print("    pixpick <image> <x-offset> <y-offset>")
        return
    
    filename = argv[1]
    xoff = int(argv[2])
    yoff = int(argv[3])

    pilImg = Image.open(filename, "r")
    pilImg.verify()
    pilImg = Image.open(filename, "r")

    img = np.asarray(pilImg, dtype=np.uint8)
    print(img[yoff][xoff])

    pilImg.close()


if __name__ == "__main__":
    main(sys.argv)

